# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=64)),
                ('track_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
    ]
