# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='prodectid1',
            new_name='productid1',
        ),
    ]
