# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20180703_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=0)),
                ('typename', models.CharField(max_length=16)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
