# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_is_select', models.BooleanField(default=True)),
                ('c_goods_nums', models.IntegerField(default=1)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Goods')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.UserInfo')),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_total_price', models.FloatField(default=0)),
                ('o_status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('o_uesr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.UserInfo')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Order')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
    ]
